# Generated by Django 4.0.1 on 2022-10-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ENTRETENIMENTO', 'ENTRETENIMENTO'), ('ALIMENTACAO', 'ALIMENTACAO'), ('TRANSPORTE', 'TRANSPORTE'), ('SAUDE', 'SAUDE'), ('EDUCAÇÃO', 'EDUCAÇÃO'), ('OUTROS', 'OUTROS')], default='6', max_length=15),
        ),
    ]
