# Generated by Django 4.0.1 on 2022-10-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='account',
        ),
        migrations.DeleteModel(
            name='Bank_Account',
        ),
    ]
